# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SDK_Line_Login' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SDK_Line_Login
pod 'LineSDK', '~> 4.1.0'

end
